/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NavbarComponent: typeof import('./src/components/NavbarComponent.vue')['default']
    PhoneComponent: typeof import('./src/components/PhoneComponent.vue')['default']
    PhoneInput: typeof import('./src/components/Inputs/PhoneInput.vue')['default']
    RequestModal: typeof import('./src/components/RequestModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    UsernameInput: typeof import('./src/components/Inputs/UsernameInput.vue')['default']
    WhatsAppComponent: typeof import('./src/components/WhatsAppComponent.vue')['default']
  }
}
