/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutUs: typeof import('./src/components/AboutUs.vue')['default']
    CalcTabs: typeof import('./src/components/CalcTabs.vue')['default']
    Contacs: typeof import('./src/components/Contacs.vue')['default']
    Floor: typeof import('./src/components/TabsVariants/Floor.vue')['default']
    KeramzitCalc: typeof import('./src/components/TabsVariants/KeramzitCalc.vue')['default']
    NavbarComponent: typeof import('./src/components/NavbarComponent.vue')['default']
    OrderComponent: typeof import('./src/components/OrderComponent.vue')['default']
    PhoneComponent: typeof import('./src/components/PhoneComponent.vue')['default']
    PhoneInput: typeof import('./src/components/Inputs/PhoneInput.vue')['default']
    ProductGrid: typeof import('./src/components/ProductGrid.vue')['default']
    Pumps: typeof import('./src/components/Pumps.vue')['default']
    RequestModal: typeof import('./src/components/RequestModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UsernameInput: typeof import('./src/components/Inputs/UsernameInput.vue')['default']
    Variant1: typeof import('./src/components/TabsVariants/Variant1.vue')['default']
    Variant2: typeof import('./src/components/TabsVariants/Variant2.vue')['default']
    Variant3: typeof import('./src/components/TabsVariants/Variant3.vue')['default']
    Variant4: typeof import('./src/components/TabsVariants/Variant4.vue')['default']
    WhatsAppComponent: typeof import('./src/components/WhatsAppComponent.vue')['default']
  }
}
